# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceMgnt', '0002_auto_20170512_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(default=300, max_length=10),
        ),
    ]
